import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import { ethers, contract } from "../utils/ethers"
import Head from 'next/head';
import styles from '../styles/Home.module.css';






const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Matching Pennies</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <div className={styles.connectButtonWrapper}>
          <ConnectButton/>
        </div>
        <h1>Matching Pennies</h1>
        <p>A blockchain based game illustrating mixed strategy Nash Equilibrium</p>
        <div className={styles.buttonRow}>
          <button>Create Game</button>
          <button>Join Game</button>
          <button>Play Game</button>
        </div>
      </main>
    </div>
  );
};

export default Home;
